AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 VM

Parameters:
  InstanceType:
    Description: EC2 type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.Small
      - t3.Medium
    
  KeyName:
    Description: Key pair for shh access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: enter valid Key Pair

  SecurityGroupIds:
    Description: security gorup for ec2
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: enter valid SG id

  ImageId:
    Type: AWS::EC2::Image::Id

  UserData:
    Type: String
    Default: ''

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIds
      ImageId: !Ref ImageId


Outputs:
  InstanceId:
    Description: ID of the instance
    Value: !Ref EC2Instance
  PublicDnsName:
    Description: DNS of the instance
    Value: !GetAtt EC2Instance.PublicDnsName